Add FIXME in regards to re-using the same output stream in MsExcelRecordWriter
Here is the patch I tried:

```diff
Index: easy-batch-extensions/easy-batch-msexcel/src/main/java/org/jeasy/batch/extensions/msexcel/MsExcelRecordWriter.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- easy-batch-extensions/easy-batch-msexcel/src/main/java/org/jeasy/batch/extensions/msexcel/MsExcelRecordWriter.java	(revision 5572e24f3a4dc74500a021a9ce77ea0ae96e2ea4)
+++ easy-batch-extensions/easy-batch-msexcel/src/main/java/org/jeasy/batch/extensions/msexcel/MsExcelRecordWriter.java	(date 1580563644516)
@@ -33,6 +33,7 @@
 import org.jeasy.batch.core.record.Record;
 import org.jeasy.batch.core.writer.RecordWriter;

+import java.io.FileNotFoundException;
 import java.io.FileOutputStream;
 import java.nio.file.Path;

@@ -49,6 +50,8 @@

     private XSSFSheet sheet;

+    private FileOutputStream fileOutputStream;
+
     /**
      * Create a new {@link MsExcelRecordWriter}.
      *
@@ -83,8 +86,8 @@
     }

     @Override
-    public void open() {
-
+    public void open() throws FileNotFoundException {
+        fileOutputStream = new FileOutputStream(path.toFile());
     }

     @Override
@@ -99,12 +102,14 @@
                 setValue(cell, nextCell);
             }
         }
-        FileOutputStream fileOutputStream = new FileOutputStream(path.toFile());
         workbook.write(fileOutputStream);
     }

     @Override
     public void close() throws Exception {
+        if (fileOutputStream != null) {
+            fileOutputStream.close();
+        }
         workbook.close();
     }
 }
```

This causes the following error to happen when
running the `MsExcelSupportIntegrationTest.integrationTest`:

```
[pool-1-thread-1] INFO org.jeasy.batch.core.job.BatchJob - Job 'job' starting
[pool-1-thread-1] INFO org.jeasy.batch.core.job.BatchJob - Job 'job' started
[pool-1-thread-1] ERROR org.jeasy.batch.core.job.BatchJob - Unable to write records
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@34f21eba
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:502)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1467)
	at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:217)
	at org.jeasy.batch.extensions.msexcel.MsExcelRecordWriter.writeRecords(MsExcelRecordWriter.java:106)
	at org.jeasy.batch.core.job.BatchJob.writeBatch(BatchJob.java:246)
	at org.jeasy.batch.core.job.BatchJob.call(BatchJob.java:112)
	at org.jeasy.batch.core.job.BatchJob.call(BatchJob.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /docProps/app.xml fail to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@34f21eba
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:490)
	... 10 more
[pool-1-thread-1] INFO org.jeasy.batch.core.job.BatchJob - Job 'job' finished with status FAILED in 184ms
```